basic function of array

In [1]:
import array
nums = array.array('i',[1,2,3,-4,5])
print(nums)

array('i', [1, 2, 3, -4, 5])


In [2]:
import array as arr
nums = arr.array('i',[1,2,3,-4,5])
print(nums)

array('i', [1, 2, 3, -4, 5])


In [4]:
from array import *
nums = array('I',[1,2,3,8,5])
print(nums)

array('I', [1, 2, 3, 8, 5])


In [5]:
from array import *
nums = array('I',[1,2,3,8,5])
nums.append(12)
print(nums)

array('I', [1, 2, 3, 8, 5, 12])


In [6]:
from array import *
nums = array('I',[1,2,3,8,5])
nums.remove(3)
print(nums)

array('I', [1, 2, 8, 5])


In [12]:
from array import *
nums = array('I',[1,2,3,8,8])
nums.remove(3)
print(nums)
print(nums.typecode)
print(nums.buffer_info())

array('I', [1, 2, 8, 8])
I
(2655588613104, 4)


In [14]:
from array import *
nums = array('I',[1,2,3,8,8])
nums.reverse()
print(nums)

array('I', [8, 8, 3, 2, 1])


In [15]:
from array import *
nums = array('I',[1,2,3,8,8])
print(nums[2])
print(nums[0])

3
1


In [4]:
from array import *
nums = array('I',[1,2,3,8,8])
for i in range(len(nums)):
    print(nums[i])

1
2
3
8
8


In [6]:
from array import *
nums = array('I',[1,2,3,8,8])
sum = 0
for i in range(len(nums)):
    sum += nums[i]
print(sum)

22


In [7]:
''' copy element '''
from array import *
nums = array('I',[1,2,3,8,8])
newArr = array(nums.typecode, (ele for ele in nums))
print(nums)
print(newArr)

array('I', [1, 2, 3, 8, 8])
array('I', [1, 2, 3, 8, 8])


taking input in arrays

In [8]:
from array import *
arr = array('i',[])
n = input('enter number of values that you want to insert: ')
print(type(n))

<class 'str'>


In [9]:
from array import *
arr = array('i',[])
n = int(input('enter number of values that you want to insert: '))
for i in range(n):
    x = int(input(f'enter {i}th number : '))
    arr.append(x)
print(arr)

array('i', [5, 31, 356, 34, 326])


In [10]:
from array import *
arr = array('i',[])
n = int(input('enter number of values that you want to insert: '))
for i in range(n):
    x = int(input(f'enter {i}th number : '))
    arr.append(x)
print(arr)
idx = 0
for ele in arr:
    if ele == -5:
        print(idx)
        break
    idx += 1

array('i', [14, 3, 31, 1, 16])


In [17]:
from numpy import *
vals = array([1,2,3,4,5,6],int)
print(vals)

[1 2 3 4 5 6]


creating numpy arrays

In [24]:
from numpy import *
vals = array([2,4,6,3.6,6])
print(vals)
print(vals.dtype)
vals = array([2,4,6,3.6,6],int)
print(vals.dtype)
print(vals)
vals = array([2,4,6,3.6,6],float)
print(vals.dtype)
print(vals)

[2.  4.  6.  3.6 6. ]
float64
int32
[2 4 6 3 6]
float64
[2.  4.  6.  3.6 6. ]


In [30]:
''' linspace '''
from numpy import *
vals = linspace(0,1,5)
print(vals)

[0.   0.25 0.5  0.75 1.  ]


In [32]:
''' logspace '''
from numpy import *
vals = logspace(1,5,5)
print(vals)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]


In [34]:
vals = logspace(1,5,5)
print(vals[4])
print('%.2f'%vals[4])

100000.0
100000.00


In [35]:
''' arange '''
vals = arange(1,20,3)
print(vals)

[ 1  4  7 10 13 16 19]


In [37]:
''' zeros and ones '''
vals = zeros(6)
print(vals)
vals = zeros(6,int)
print(vals)

[0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0]


basic functionality of functional array

In [39]:
from numpy import *
arr1 = array([1,2,3])
arr2 = array([4,5,6])
arr = arr1 + arr2
print(arr)

[5 7 9]


In [41]:
from numpy import *
arr1 = array([1,2,3])
arr2 = array([4,5,6])
arr3 = arr1 + 7
print(arr3)
arr3 = arr1 * 7
print(arr3)

[ 8  9 10]
[ 7 14 21]


In [44]:
from numpy import *
arr1 = array([1,2,3])
arr2 = array([4,5,6])
print(sin(arr2))
print(cos(arr2))
print(tan(arr2))

[-0.7568025  -0.95892427 -0.2794155 ]
[-0.65364362  0.28366219  0.96017029]
[ 1.15782128 -3.38051501 -0.29100619]


In [47]:
from numpy import *
arr1 = array([1,2,3])
arr2 = array([4,5,6])
print(sqrt(arr1))

[1.         1.41421356 1.73205081]


In [48]:
from numpy import *
arr1 = array([1,2,3])
arr2 = array([4,5,6])
print(max(arr1))

3


In [49]:
from numpy import *
arr1 = array([1,2,3])
arr2 = array([4,5,6])
print(concatenate([arr1,arr2]))

[1 2 3 4 5 6]


In [50]:
from numpy import *
arr1 = array([1,2,3])
arr2 = array([4,5,6])
print(id(arr1))
print(id(arr2))

3053912785232
3053912786960


shallow copy

In [52]:
from numpy import *
arr1 = array([1,2,3])
arr2 = arr1.view()
print(id(arr1))
print(id(arr2))
print(arr1)
print(arr2)
arr1[2] = 6
print(arr2)

3053912788976
3053912788016
[1 2 3]
[1 2 3]
[1 2 6]


deep copy

In [54]:
from numpy import *
arr1 = array([1,2,3])
arr3 = arr1.copy()
print(arr1)
print(arr3)
arr1[1] = 5
print(arr1)
print(arr3)

[1 2 3]
[1 2 3]
[1 5 3]
[1 2 3]
