In [30]:
from numpy import *
# array
arr = array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [31]:
arr = array(30)
print(arr)
print(type(arr))
print(arr.dtype)

30
<class 'numpy.ndarray'>
int32


In [32]:
arr = array([1,2,3,4,6],int)
print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3 4 6]
<class 'numpy.ndarray'>
int32


In [33]:
arr = array([1,2,3,4,6],float)
print(arr)
print(type(arr))
print(arr.dtype)

[1. 2. 3. 4. 6.]
<class 'numpy.ndarray'>
float64


In [34]:
arr = array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(type(arr))
print(arr.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
int32


creating numpy array using llinspace

In [35]:
from numpy import *
arr = linspace(0,49)
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]


In [36]:
from numpy import *
arr = linspace(0,49,num = 5)
print(arr)

[ 0.   12.25 24.5  36.75 49.  ]


In [37]:
from numpy import *
arr = linspace(0,49,num=5,endpoint=False)
print(arr)

[ 0.   9.8 19.6 29.4 39.2]


creating numpy arrays using logaspace

In [38]:
from numpy import *
arr = logspace(1,2,num=5)
print(arr)
# start = base ** start
# end = base ** end

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


In [39]:
from numpy import *
arr = logspace(1,2,num=5,base=2)
print(arr)
# start = base ** start
# end = base ** end

[2.         2.37841423 2.82842712 3.36358566 4.        ]


creating numpy arrays using arange

In [40]:
from numpy import *
# Arange
arr = arange(8)
print(arr)

[0 1 2 3 4 5 6 7]


In [41]:
from numpy import *
# Arange
arr = arange(3,7)
print(arr)

[3 4 5 6]


In [42]:
from numpy import *
# Arange
arr = arange(1,15,step=2)
print(arr)

[ 1  3  5  7  9 11 13]


In [43]:
from numpy import *
# Arange
arr = arange(1,15,step=2,dtype=float)
print(arr)

[ 1.  3.  5.  7.  9. 11. 13.]


In [44]:
from numpy import *
# zeors/ones
arr = zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [45]:
from numpy import *
# zeors/ones
arr = zeros(5,dtype=int)
print(arr)

[0 0 0 0 0]


In [46]:
from numpy import *
# zeors/ones
arr = zeros((5,2),dtype=int)
print(arr)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [47]:
from numpy import *
# zeors/ones
arr = ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [48]:
from numpy import *
# zeors/ones
arr = ones((5,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [49]:
from numpy import *
# zeors/ones
arr = ones((5,2),dtype=int)
print(arr)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


creating numpy arrays using some other methods

In [50]:
from numpy import *
# eye
arr = eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [51]:
from numpy import *
# eye
arr = eye(4,dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [29]:
from numpy import *
# eye
arr = eye(4,dtype=int,k=2)
print(arr)

[[0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]]


In [54]:
from numpy import *
# array
arr = array([5,7,4,1,8])
print(arr)
print(max(arr))
print(min(arr))
print(sort(arr))

[5 7 4 1 8]
8
1
[1 4 5 7 8]


In [55]:
from numpy import *
# array
arr = array([5,7,4,1,8])
arr += 5
print(arr)

[10 12  9  6 13]


In [56]:
from numpy import *
# array
arr = array([5,7,4,1,8])
arr *= 5
print(arr)

[25 35 20  5 40]
